### ISSUE TITLE
Switch ripple positions need to be offset due to the fix implemented in #10

### ISSUE THREAD

**Issue by Oj18** [oojmed/OojmedChat-Web#12]
See comment(s): #10

**Comment by Oj18** [comment]
Can be solved by adding a margin, as can be seen below:
```css
.mdl-switch__ripple-container {
  width: 24px !important;
  height: 24px !important;

  margin: 12px 0px 0px 12px;
}
```
